# Configuração do Netlify para projeto vanilla (sem build)

[build]
  # Sem comando de build - projeto usa HTML/CSS/JS puros
  command = ""
  # Publica da raiz do projeto onde está o index.html
  publish = "."

# Configurações de ambiente
[build.environment]
  NODE_VERSION = "18"

# Redirecionamento SPA - todas as rotas vão para index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"

# Cache para arquivos JavaScript
[[headers]]
  for = "/src/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para arquivos CSS
[[headers]]
  for = "/styles/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Sem cache para index.html
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Sem cache para importar.html
[[headers]]
  for = "/importar.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
